# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upload2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(434, 215)
        self.textEditName = QtWidgets.QTextEdit(Form)
        self.textEditName.setGeometry(QtCore.QRect(90, 60, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEditName.setFont(font)
        self.textEditName.setObjectName("textEditName")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(90, 100, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.nameLabel = QtWidgets.QLabel(Form)
        self.nameLabel.setGeometry(QtCore.QRect(20, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.artistLabel = QtWidgets.QLabel(Form)
        self.artistLabel.setGeometry(QtCore.QRect(20, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.artistLabel.setFont(font)
        self.artistLabel.setObjectName("artistLabel")
        self.coverLabel = QtWidgets.QLabel(Form)
        self.coverLabel.setGeometry(QtCore.QRect(20, 140, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.coverLabel.setFont(font)
        self.coverLabel.setObjectName("coverLabel")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(90, 140, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.coverLabelInfo = QtWidgets.QLabel(Form)
        self.coverLabelInfo.setGeometry(QtCore.QRect(190, 140, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.coverLabelInfo.setFont(font)
        self.coverLabelInfo.setText("")
        self.coverLabelInfo.setObjectName("coverLabelInfo")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(330, 180, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.selectedFileInfo = QtWidgets.QLabel(Form)
        self.selectedFileInfo.setGeometry(QtCore.QRect(20, 10, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectedFileInfo.setFont(font)
        self.selectedFileInfo.setObjectName("selectedFileInfo")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.nameLabel.setText(_translate("Form", "Name:"))
        self.artistLabel.setText(_translate("Form", "Artist:"))
        self.coverLabel.setText(_translate("Form", "Cover:"))
        self.pushButton.setText(_translate("Form", "Upload"))
        self.pushButton_2.setText(_translate("Form", "Ok"))
        self.selectedFileInfo.setText(_translate("Form", "Name of selected file mp3"))
