from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(434, 215)
        Form.setStyleSheet("background-color: #323232")
        self.nameLabel = QtWidgets.QLabel(Form)
        self.nameLabel.setGeometry(QtCore.QRect(20, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("color:#fff;")
        self.nameLabel.setObjectName("nameLabel")
        self.artistLabel = QtWidgets.QLabel(Form)
        self.artistLabel.setGeometry(QtCore.QRect(20, 100, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.artistLabel.setFont(font)
        self.artistLabel.setStyleSheet("color:#fff;")
        self.artistLabel.setObjectName("artistLabel")
        self.coverLabel = QtWidgets.QLabel(Form)
        self.coverLabel.setGeometry(QtCore.QRect(20, 140, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.coverLabel.setFont(font)
        self.coverLabel.setStyleSheet("color:#fff;")
        self.coverLabel.setObjectName("coverLabel")
        self.pushButton_Cover = QtWidgets.QPushButton(Form)
        self.pushButton_Cover.setGeometry(QtCore.QRect(90, 140, 89, 25))
        self.pushButton_Cover.setObjectName("pushButton_Cover")
        self.pushButton_Cover.setStyleSheet("background: #fff; color:#000;")
        self.coverLabelInfo = QtWidgets.QLabel(Form)
        self.coverLabelInfo.setGeometry(QtCore.QRect(190, 140, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.coverLabelInfo.setFont(font)
        self.coverLabelInfo.setStyleSheet("color:#fff;")
        self.coverLabelInfo.setText("")
        self.coverLabelInfo.setObjectName("coverLabelInfo")
        self.pushButton_Ok = QtWidgets.QPushButton(Form)
        self.pushButton_Ok.setGeometry(QtCore.QRect(330, 180, 89, 25))
        self.pushButton_Ok.setObjectName("pushButton_Ok")
        self.pushButton_Ok.setStyleSheet("background: #fff; color:#000;")
        self.selectedFileInfo = QtWidgets.QLabel(Form)
        self.selectedFileInfo.setGeometry(QtCore.QRect(20, 10, 401, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectedFileInfo.setFont(font)
        self.selectedFileInfo.setStyleSheet("color:#fff;")
        self.selectedFileInfo.setObjectName("selectedFileInfo")
        self.lineEditName = QtWidgets.QLineEdit(Form)
        self.lineEditName.setGeometry(QtCore.QRect(90, 60, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditName.setFont(font)
        self.lineEditName.setStyleSheet("background: #fff; color:#000;")
        self.lineEditName.setObjectName("lineEditName")
        self.lineEditArtist = QtWidgets.QLineEdit(Form)
        self.lineEditArtist.setGeometry(QtCore.QRect(90, 100, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditArtist.setFont(font)
        self.lineEditArtist.setStyleSheet("background: #fff; color:#000;")
        self.lineEditArtist.setObjectName("lineEditArtist")
        self.pushButton_Skip = QtWidgets.QPushButton(Form)
        self.pushButton_Skip.setGeometry(QtCore.QRect(10, 180, 89, 25))
        self.pushButton_Skip.setObjectName("pushButton_Skip")
        self.pushButton_Skip.setStyleSheet("background: #fff; color:#000;")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.nameLabel.setText(_translate("Form", "Name:"))
        self.artistLabel.setText(_translate("Form", "Artist:"))
        self.coverLabel.setText(_translate("Form", "Cover:"))
        self.pushButton_Cover.setText(_translate("Form", "Upload"))
        self.pushButton_Ok.setText(_translate("Form", "Ok"))
        self.selectedFileInfo.setText(_translate("Form", "Name of selected file mp3"))
        self.pushButton_Skip.setText(_translate("Form", "Skip all"))
